package verify.jboss.drools.simple

rule "the first rule"
	when
	 $t :	Transaction(type == "WithDraw", amount > 50000)
	then
		System.out.println("you need submit a application firstly.");
end

rule "the not first rule"

	when
		not Transaction()
	then
		System.out.println("System can not handle non transaction object.");
		System.out.println("Please contact administrator.");
	end	
	